### ISSUE TITLE
Image built from Dockerfile does not run, image download from Docker Hub does...

### ISSUE THREAD

**Issue by airbrain-org** [frxyt/docker-xrdp#1]
When I rebuild the image using Dockerfile, "sessman" indicates that there is a security error when attempting to connect to VNC.  This error is not present, however, when I simply run the image in Docker Hub.  In both cases, I am using exactly the same "docker run" command parameters.

Is there anything that you added to the image on Docker Hub that is not represented in github?

Many thanks for making this available.  Of all the docker images available with xrdp on Docker Hub this is by far the most useful.

Thanks again,

Jim W.

**Comment by golflima** [comment]
Hi,
The image on Docker Hub is directly built from this repository by Docker Hub itself, so everything there is here.
Maybe a package update since the last time the image was built broke something, I'll need to have a look.

**Comment by airbrain-org** [comment]
Okay, thanks for checking.  Let me know if I can help.

**Comment by golflima** [comment]
Hello,
I just found some time to test it on my side. Everything works fine, from the local build to the execution & use of the image. But I only test with cinnamon desktop.
Which variant do you use ? Can you please paste here the logs of the error (docker output should be enough). Can you also give me the command you use to build it locally ?
Best regards,
Jeremy.

**Comment by airbrain-org** [comment]
Will do.  I was using the xfce desktop.  I will test cinnamon as well.

It wasn't clear to me how to select different desktops at build time.  Is
this another environment variable.

**Comment by golflima** [comment]
You can use:

```
docker build -f Dockerfile -t frxyt/xrdp:cinnamon --build-arg DOCKER_TAG=cinnamon .
docker build -f Dockerfile -t frxyt/xrdp:lxde --build-arg DOCKER_TAG=lxde .
docker build -f Dockerfile -t frxyt/xrdp:mate --build-arg DOCKER_TAG=mate .
docker build -f Dockerfile -t frxyt/xrdp:xfce --build-arg DOCKER_TAG=xfce .
```

**Comment by golflima** [comment]
Any news ? Can I close this issue?

**Comment by airbrain-org** [comment]
Sorry that I took so long to reply.  I will go ahead and close the issue.  

I found that I was failing to map in a home directory from the host.  This caused sessman to fail whenever I restarted the image from a previously committed container.  The first run of the newly built image always succeeded, however, which was very confusing at first.

Thanks for your help!
